### ISSUE TITLE
Weapon spread/recoil does not reduce when not firing

### ISSUE THREAD

**Issue by brandonator365** [SquidingTin/COR#1]
### Details
When using any weapon that builds weapon spread over time (the recoil mechanic), this spread does not decrease when the weapon stops being fired. This applies to every COR weapon I've tested so far, and seems to be linked to the weapon itself. For example, if someone else picks up that same weapon, the inaccuracy will still be the same, and will not recover under any circumstances. This makes most weapons completely unusable, or at least very inconvenient.

### Steps to Reproduce
1. Get a firearm.
2. Shoot it.
3. Wait patiently.

### Demonstration
Weapon skill was 100 for this demonstration.
![COR Recoil Issue](https://github.com/SquidingTin/COR/assets/17090456/cee5f33d-a972-4a2a-968d-ab1f0fcd7e02)

**Comment by SquidingTin** [comment]
Fixed awhile ago, forgot to close this
